- gradient-aws/main.tf
- gradient-metal/main.tf
- modules/gradient-processing/templates/values.yaml.tpl
Required to stay in sync with changes in https://github.com/Paperspace/gradient-processing-chart/pull/16 and https://github.com/Paperspace/gradient-processing-chart/pull/20.
> fix(monitoring): upgrade kube-state-metrics section key PS-13652 PS-13695

- README.md
Clarifies how to think about this repo, in conjunction with https://github.com/Paperspace/Docs/pull/33/.
> docs: clarify what Gradient Installer is, relative to Terraform

- cmd/gradient-installer/main.go
- modules/gradient-processing/templates/values.yaml.tpl
- pkg/cli/commands/clusters/register.go
- pkg/cli/commands/clusters/up.go
- pkg/cli/context.go
Passes ctx for register command in up command. Update logs host format.
> Fix: pass ctx to register

- gradient-aws/main.tf
Updates the aim of #4 against the current codebase.
> feat(aws): Increase default Kubernetes version to 1.15.

- gradient-aws/input.tf
- gradient-aws/main.tf
- modules/gradient-processing/input.tf
- modules/gradient-processing/main.tf
- modules/gradient-processing/templates/values.yaml.tpl
Pass down the New Relic configuration for monitoring.
> feat: Add optional New Relic monitoring configuration

- .circleci/config.yml
- gradient-ps-cloud/main.tf
- modules/gradient-processing/input.tf
- modules/gradient-processing/main.tf
- modules/gradient-processing/templates/values.yaml.tpl
Updates to latest Paperspace cluster-autoscaler. Lowers scale-down delay after scale-up to 2 minutes from 8, since this value applies across ASGs. Fixes CLD-149.
> fix(ps-cloud): Update autoscaler and scale-down settings.

- gradient-aws/modules/kubernetes/main.tf
After, I'm going to tag this as 0.6.0.
> Remove unsupported labels in 1.16

- .circleci/config.yml
Our rancher provider is not compatible.
> feat: drop support for terraform 12

- gradient-ps-cloud/main.tf
- gradient-ps-cloud/templates/setup-script.tpl
Reverts Paperspace/gradient-installer#141
> Revert "Revert "fix(ps-cloud): add reservations for kubelet to improve node stability CLD-308""

- gradient-ps-cloud/main.tf
> fix: increase ephemeral storage reservation

- modules/gradient-processing/templates/values.yaml.tpl
Prometheus resources should be deployed to the services pool.
> fix(prometheus): fix node selector

- modules/gradient-processing/templates/values.yaml.tpl
> fix(prometheus/traefik): revert resource changes for prometheus and traefik

- gradient-metal/common.tf
- gradient-ps-cloud/common.tf
- gradient-ps-cloud/input.tf
- gradient-ps-cloud/main.tf
Add  jupyter/datascience-notebook to image cache. Refactor so that common.tf is maintained by make sync_copy
> Add jupyter notebook to cache

- gradient-ps-cloud/main.tf
> fix: disable kubefledged

- .circleci/config.yml
- Dockerfile
Sets terraform 1.0.0 as the default terraform version
> Add terraform 1.0.0 compat

- gradient-ps-cloud/input.tf
- gradient-ps-cloud/main.tf
Reverts Paperspace/gradient-installer#186
> Revert "fix(coredns): make coredns select service nodes"

- gradient-ps-cloud/main.tf
- modules/gradient-processing/templates/values.yaml.tpl
awaiting corresponding autoscaler tag...
> add Free-A100

- pkg/cli/commands/clusters/register.go
- pkg/cli/terraform/commands.go
1.0.10 is latest terraform version and container registry is no longer in use
> Update terraform version to 1.0.10 and remove container registry prompts PLA-505 PLA-504

- gradient-ps-cloud/input.tf
- gradient-ps-cloud/lb.tf
- gradient-ps-cloud/main.tf
- gradient-ps-cloud/service.tf
- modules/pool-overprovisioner/input.tf
- modules/pool-overprovisioner/main.tf
also includes terraform fmt changes
> Pool overprovisioner

- gradient-aws/modules/kubernetes/README.md
- gradient-aws/modules/kubernetes/cpu-instance-vars.tf
- gradient-aws/modules/kubernetes/gpu-instance-vars.tf
- gradient-aws/modules/kubernetes/input.tf
- gradient-aws/modules/kubernetes/main.tf
- gradient-aws/modules/kubernetes/output.tf
- gradient-ps-cloud/main.tf
- modules/gradient-processing/templates/values.yaml.tpl
- modules/pool-overprovisioner/input.tf
- Light Variable/Locals Refactoring
- https://github.com/Paperspace/gradient-installer/issues/243 is addressed
- README init for module (I would like to begin to bubble up module inputs and outputs)
- Adding `worker_group` `list(map(any))` as module output
> feat(gradient-aws-kubernetes): refactor

- go.mod
- pkg/cli/commands/clusters/register.go
Happy Path:
Unhappy Path:
Closes #252
> chore(register): add s3 validation

- pkg/cli/commands/clusters/register.go
- pkg/cli/terraform/base.go
Adding bucket prompt, still need pass region down to terraform-land.
> feat(register): adding region prompt

- pkg/cli/commands/clusters/up.go
- pkg/cli/config/profile.go
- pkg/cli/terraform/metalPlatform.go
- Making SSHKeyPath optional
- Adding paperspace api key override
> chore(gradient-installer): optional ssh key path

- modules/gradient-processing/templates/values.yaml.tpl
> chore(recycle-bin): bump cpu req

- gradient-ps-cloud/admin.tf
- gradient-ps-cloud/input.tf
- gradient-ps-cloud/main.tf
- gradient-ps-cloud/templates/setup-script.tpl
Need an admin box for scripty things, because doing it on a load balancer is janky.
> feat(gradient): adding optional admin box

- gradient-ps-cloud/admin.tf
- gradient-ps-cloud/config.tf
- gradient-ps-cloud/input.tf
- gradient-ps-cloud/lb.tf
- gradient-ps-cloud/main.tf
- gradient-ps-cloud/prometheus.tf
- gradient-ps-cloud/service.tf
- gradient-ps-cloud/templates/setup-script.tpl
- gradient-ps-cloud/tests/Makefile
- gradient-ps-cloud/tests/main.tf
- Bumping cloudflare version
- Fixing templating for new variables
- Adding configurable admin kube worker node
> fix(gradient-ps-cloud): re-adding admin box

- gradient-ps-cloud/common.tf
- gradient-ps-cloud/special_nodes.tf
- gradient-ps-cloud/tests/Makefile
- Add a proper suffix to the bastion hosts 
- Add a notebook workspace specific node to short circuit scheduling
> feat(gradient-installer): adding workspace specific node

- gradient-ps-cloud/main.tf
For fixes around stuck in terminating pods.
> chore: upgrade to kube 1.20.15

- gradient-ps-cloud/input.tf
> chore(ps-cloud): default enable workspace vm

- modules/gradient-processing/input.tf
- modules/gradient-processing/main.tf
- modules/gradient-processing/output.tf
- modules/gradient-processing/templates/values.yaml.tpl
The twin to the chart changes to enable this feature.
> feat(victoria-metrics): distributed victoria

- modules/gradient-processing/templates/values.yaml.tpl
> hotfix(vmstorage): ooming in production

- gradient-ps-cloud/main.tf
- modules/gradient-processing/templates/values.yaml.tpl
Coordinated effort to deploy new paperspace machine types on Gradient.
> chore(installer): hugging face new machine types

- modules/gradient-processing/templates/values.yaml.tpl
Sharing is caring and the node for our metrics is a beast. I'm going to vertically scale until we reach a happy medium.
> chore(victoria): sharing is caring in prod

- modules/gradient-processing/input.tf
- modules/gradient-processing/main.tf
- modules/gradient-processing/templates/values.yaml.tpl
Can start with some hard config.
> chore(vmagent): more kubelet, more deployments

- modules/gradient-processing/input.tf
In production the third replica for vmselect is crashing consistently.
> fix(prod): third replica crashing, reverting

- modules/gradient-processing/templates/values.yaml.tpl
> chore: remove retired gradient v2 services

- gradient-ps-cloud/input.tf
- gradient-ps-cloud/main.tf
- modules/gradient-processing/input.tf
- modules/gradient-processing/main.tf
- modules/gradient-processing/templates/values.yaml.tpl
Allows New Relic configs to be passed down to the Volume FS API to be monitored.
> feat(volume-fs): Add volumeFs new relic config variables

- gradient-ps-cloud/main.tf
- modules/gradient-processing/templates/values.yaml.tpl
We are experiencing latency spikes in treafik. The memory and cpu look ok during these times and the last time we had issues with traefik the boxes link was nearing being overwhelmed.
> fix(traefik): HA load-balancing in multi-node PLA-1125

- modules/gradient-processing/templates/values.yaml.tpl
> chore: nfs storage config

- common/common.tf
- gradient-aws/common.tf
- gradient-metal/common.tf
- gradient-ps-cloud/common.tf
- gradient-ps-cloud/input.tf
- modules/gradient-processing/templates/values.yaml.tpl
Ticket: https://linear.app/paperspace/issue/PLA-1155/gradient-installer-metal-cluster-up-fails-with-message-failed-parsing
> sanfilip fix failed parsing key volume fs.new relic.license key PLA-1155

- gradient-ps-cloud/main.tf
- modules/gradient-processing/templates/values.yaml.tpl
and bump cache concurrency to 20
> chore: add new rapids runtime to cache list

- modules/gradient-processing/templates/values.yaml.tpl
It should run in an HA configuration in the public cluster.
> chore(gradient-processing): increase volume-fs replicas

- common/common.tf
- gradient-aws/common.tf
- gradient-metal-gc/common.tf
- gradient-metal-gc/input.tf
- gradient-metal-gc/main.tf
- gradient-metal/common.tf
- gradient-ps-cloud/common.tf
- modules/external-ingress/main.tf
- modules/gradient-processing/input.tf
- modules/gradient-processing/main.tf
- modules/gradient-processing/templates/values.yaml.tpl
Create a terraform module that wraps the necessary config to add tls
termination and load balancing external to the cluster ip addresses.
This is to support public datasets on graphcore clusters with minimal
latency.
> feat(gradient-metal-gc): add ingress for DC local s3 service PLA-1895

- common/common.tf
- gradient-aws/common.tf
- gradient-metal-gc/common.tf
- gradient-metal/common.tf
- gradient-ps-cloud/common.tf
- modules/gradient-processing/input.tf
- modules/gradient-processing/main.tf
- modules/gradient-processing/templates/values.yaml.tpl
See also https://github.com/Paperspace/PS_API/pull/4215
> fix: parameterize vmsingle resources so graphcore prod can override

- gradient-metal-gc/ansible/roles/gradient_common/tasks/install_kubelet_config.yml
> Fix typos & remove quotes from kubelet-config

- gradient-ps-cloud/main.tf
Last night's incident was worsened by 1 node failing and causing critical performance problems for the others.
> chore: increase kube api servers SIT-200

- .github/workflows/pr.yml
- gradient-aws/main.tf
Also make sure CI fails if the TF module is invalid this means removing the plan step since it never succeeded because of a lot of missing production credentials. This plan step is questionably useful anyway since its always starting from scratch on a dummy cluster and doesn't show what would happen against a real target.
> fix(aws): provider config so tests pass

- modules/gradient-processing/templates/values.yaml.tpl
Also nest it properly so the config is picked up by the chart.
> chore: increase dispatcher resources

- gradient-ps-cloud/main.tf
> chore: boost vc resources

- gradient-ps-cloud/main.tf
Add sleep to ensure apt upgrade
> chore: add sleep to ensure apt upgrade

- modules/node-problem-detector/main.tf
- modules/node-problem-detector/templates/values.json.tpl
So it actually completes in a reasonable amount of time.
> fix(node-problem-detector): improve rollout params

- gradient-ps-cloud/templates/setup-script.tpl
I tested this new startup script on a new C4 worker and P4000 worker in staging. They came up and I ran a notebook on both.
> fix(cluster-installer): address log error in startup script SIT-392

- gradient-ps-cloud/files/linux-guest-health.sh
Reverts Paperspace/cluster-installer#447
> Revert "fix(ps-cloud): make guest health checks more resilient SIT-372"

- gradient-ps-cloud/input.tf
Ubuntu 22.04 seems to need more
> chore(ps-cloud): increase lb storage

- modules/gradient-processing/templates/values.yaml.tpl
Templating issue made this setting revert to the default
> fix(graphcore): disable bad nodes

- gradient-ps-cloud/resources.tf
https://digitalocean.slack.com/archives/C0664BZE89M/p1703365256555419
> chore: more dispatcher resources
