gradient-metal/common.tf
gradient-metal/input.tf
gradient-metal/main.tf
gradient-metal/modules/kubernetes/input.tf
gradient-metal/modules/kubernetes/main.tf

Expands ssh_key_path to its contents, or accepts ssh_key content
directly.
Renamed var & comments to clarify that it's a private key needed for metal installs.
Also removed unused public_key_path from metal-k8s.

refactor(metal): allow ssh_key contents to be passed in by string

---

.circleci/config.yml
.dockerignore
Dockerfile-ps-cloud
bin/setup
gradient-ps-cloud/backends/managed.tf
gradient-ps-cloud/bin/run
gradient-ps-cloud/input.tf
gradient-ps-cloud/main.tf

This PR creates a new SSH key dynamically, ensures that ansible uses that, and then writes that private ssh-key back as a secret to the team's secrets.
This eliminates the need to pass in ssh keys.
It also writes the cluster's kubeconfig as a cluster secret and the cluster id back to the cluster.
It also adds terraform various `depends_on`s to make sure the DAG runs in a good order.
Co-authored-by: Philip Reichenberger <philip@paperspace.com>
Co-authored-by: Jared Scheib <jared.scheib@gmail.com>

feat(ps-cloud): managed ps-cloud install with ansible, published as a container

---

.circleci/config.yml

Now that the main branch (`master`) is functional and relatively stable, we don't want to re-build the image at every branch push. cc @reynld to be aware on the API side, since we're consuming the latest image there.

ci(ps-cloud): only build & push installer image from main ('master') branch PS-14492

---

gradient-ps-cloud/bin/run

By default, running the terraform argo job will run `terraform apply`.  However, if you pass in `TERRAFORM_COMMAND=destroy`,  it will destroy the resources that terraform created: machines, dns records, etc.

feat(ps-cloud): ability to delete managed terraform cluster by env var PS-14546

---

README.md
cmd/gradient-installer/main.go
go.mod
go.sum
pkg/cli/commands/clusters.go
pkg/cli/commands/clusters/down.go
pkg/cli/commands/clusters/list.go
pkg/cli/commands/clusters/register.go
pkg/cli/commands/clusters/up.go
pkg/cli/commands/setup.go
pkg/cli/commands/update.go
pkg/cli/config/profile.go
pkg/cli/context.go
pkg/cli/prompt.go
pkg/cli/terraform/base.go
pkg/cli/terraform/commands.go
pkg/cli/terraform/common.go

When creating a cluster we need to prompt for container registry credentials so that features like notebook snapshotting are functional.
To run this branch:
1. `brew install go`
2. `git clone git@github.com/Paperspace/gradient-installer.git`
3. `cd gradient-installer`
4. `git checkout feat-container-registry`
5. `go run ./cmd/gradient-installer clusters up`
QA Test Plan:
1. Create a cluster on AWS with a container registry
(use the container registry info from the `staging-ps-aws cluster` in 1password)
2. Launch a notebook, pip install a package, stop the notebook
3. Restart the same notebook and verify that the same pip package is installed in the container.
4. `go run ./cmd/gradient-installer clusters down <handle>`

feat: container registry credentials N-34

---

modules/gradient-processing/main.tf
modules/gradient-processing/templates/values.yaml.tpl

This is dependent on chart template changes for 5 other repos to work fully, but this check-in should be safe to go first.
gradient-experiment-watcher
gradient-model-deployment-watcher
gradient-operator-dispatcher
gradient-operator
gradient-tensorboard-watcher
Each of the above repos will have a new deployment template annotation similar to this:
template:
metadata:
annotations:
{{- if .Values.global.gradientProcessingSecretChecksum }}
paperspace.com/secret-checksum: {{ .Values.global.gradientProcessingSecretChecksum }}
{{- end }}
I've checked the behavior of several other api-key secret references, for prometheus ingress, fluent-bit, and the new heartbeat cron job, and they all work appropriately already.
I've tested this locally and it works upon running the following twice in a row: …

add checksum global value for gradient-processing secret

---

modules/gradient-processing/templates/values.yaml.tpl

Maintain default configuration from the parent chart. Maintain ingress false since no external access is needed.

bug(metrics): Update the default values for the Pushgateway

---

gradient-ps-cloud/main.tf
gradient-ps-cloud/templates/setup-script.tpl

Reverts Paperspace/gradient-installer#139
Free-CPU nodes are too small to actually schedule anything on after making system reservations.

Revert "fix(ps-cloud): add reservations for kubelet to improve node stability CLD-308"

---

gradient-ps-cloud/main.tf
modules/gradient-processing/input.tf
modules/gradient-processing/main.tf
modules/gradient-processing/templates/values.yaml.tpl

We moved lower defaults to the processing chart and want to override them here.

fix(traefik/prometheus): adjust traefik and prom reservations if running a public cluster

---

gradient-ps-cloud/main.tf

This PR updates cached images to those that satisfy two criteria:
1. Are currently used in a Recommended or All tile in the console
2. Are used with regularity
Diff as follows. 
`>` = currently used in Recommended or All tile in the console
`+` = on list of most pulled containers when starting notebooks
```
"ufoym/deepo:all-py27-jupyter",
+   >   "tensorflow/tensorflow:2.4.1-gpu-jupyter",
"tensorflow/tensorflow:2.0.0a0-py3-jupyter",
"tensorflow/tensorflow:1.5.0-py3",
"tensorflow/tensorflow:1.5.0-gpu-py3",
+   >   "paperspace/transformers-gpu:0.4.0",
"paperspace/gradient-base:tf24-py38-0.10-small",
+   >   "paperspace/gradient-base:tf24-py36-0.10",
"paperspace/gradient-base:tf115-py36-0.10",
+   >   "paperspace/fastai:2.0-CUDA9.2-fastbook-v0.1.0",
+   > …
```

Update cached images

---

common/common.tf
gradient-aws/common.tf
gradient-aws/main.tf
gradient-aws/tests/main.tf
gradient-metal/common.tf
gradient-metal/main.tf
gradient-metal/tests/main.tf
gradient-ps-cloud/common.tf
gradient-ps-cloud/main.tf
gradient-ps-cloud/tests/main.tf
modules/gradient-processing/input.tf
modules/gradient-processing/main.tf
pkg/cli/terraform/common.go

Allows a terraform variable to be passed through and set to a secret for the processing chart to load.
Tested by deploying to the public cluster.

feat(cluster-token): add cluster_authorization_token parameter

---

modules/gradient-processing/main.tf

Its not properly set up and may be causing memory leaks and increased errors on updated fluent-bit.

fix: disable elastic search

---

go.mod
go.sum
pkg/cli/commands/clusters/up.go
pkg/cli/terraform/common.go

We added a secret to facilitate secure messaging between the cluster and APIs.

fix(auth): pass the cluster secret through to terraform when using cli

---

gradient-ps-cloud/main.tf

This is enabling C3 for all managed clusters, not just "paperspace-public".

add C3 machine type to ps-cloud cluster type

---

gradient-ps-cloud/main.tf

We run a static number of service nodes. Since moving coredns to service nodes, we dont have enough resources. Bumping to 8 will hopefully be enough.

fix(nodes): bump service nodes to 8

---

modules/gradient-processing/templates/values.yaml.tpl

On private clusters the whole body of the `volumeController` object is omitted leaving the invalid yaml `volumeController:\n` put a key in there so its always valid

fix(gradient-processing): template volumeController correctly

---

gradient-ps-cloud/main.tf
modules/gradient-processing/templates/values.yaml.tpl

c3 is too under-powered to run user workloads and gradient background processes.

chore: use c4 instead of c3

---

modules/gradient-processing/templates/values.yaml.tpl

tag should match version here: https://github.com/Paperspace/autoscaler/commit/c1bf54b37714f2683cb31e3db71e07c39183a2d7

use cluster-autoscaler tag with version setting Free-CPU to C4 specs

---

gradient-ps-cloud/main.tf

image changes : https://github.com/Paperspace/notebook_idle/pull/3
sends a rabbit mq notebook teardown message instead of shutting down via jupyter api call

feat(notebooks): update notebook-idle cached image

---

modules/pool-overprovisioner/input.tf

Couldn't run gradient-installer on public without this.

fix(pool-overprovisioner): default for overprovision map

---

go.mod
pkg/cli/commands/clusters/register.go

Thought it would be nice to have some feedback about whether your credentials work.
This is also ahead of #252 and #253 where I was thinking we would optionally allow clients to create the artifact buckets through our installer instead of requiring it already exist.
Happy Path:
Sad Path:

chore(register): add identity resolution

---

modules/gradient-processing/templates/values.yaml.tpl

Disable abuse watcher, the operator version is not compatible with kube 1.20 and this will free resources

chore: increase memory for gradient-operator services PLA-572

---

modules/gradient-processing/templates/values.yaml.tpl

The `ceph-csi-rbd-provisioner` has been stuck in a crashbackoffloop on the public cluster because two of the containers consistently OOM during boot.

chore(gradient-processing): overrides for csi-provisioner

---

gradient-ps-cloud/input.tf
gradient-ps-cloud/special_nodes.tf

Staging and production are in a bit of a weird state as of today's upgrades. I want to update them with this release, disabling these boxes and re-enabling them after. 
Fixing a var as well.

chore(gradient-installer): disable special nodes

---

gradient-ps-cloud/special_nodes.tf

Err:
```
│ Error: Invalid index
│ 
│   on special_nodes.tf line 36, in resource "paperspace_machine" "gradient_workspace_node":
│   36:   script_id        = paperspace_script.gradient_machine_setup[0].id
│     ├────────────────
│     │ paperspace_script.gradient_machine_setup is empty tuple
│ 
│ The given key does not identify an element in this collection value: the
│ collection has no elements.
```

fix(ps-cloud): bad script id

---

modules/gradient-processing/input.tf
modules/gradient-processing/templates/values.yaml.tpl

Templating was originally:
```
vmcluster:
enabled: true
vmselect:
replicaCount: 2
nodeSelector:
paperspace.com/pool-name: prometheus
storage:
storageClassName: "gradient-processing-local"
vmstorage:
replicaCount: 2
storageDataPath: "/vm-data"
nodeSelector:
paperspace.com/pool-name: prometheus
storage:
resources:
requests:
storage: 100Gi
volumeClaimTemplate:
spec:
storageClassName: "gradient-processing-rbd"
```
And didn't take affect correctly.

hotfix(gradient-installer): storage class templating

---

modules/gradient-processing/templates/values.yaml.tpl

victoria's vmstorage cache is running hot!
```
kubectl top pod vmstorage-gradient-processing-victoria-metrics-0 
NAME                                               CPU(cores)   MEMORY(bytes)   
vmstorage-gradient-processing-victoria-metrics-0   617m         9108Mi          
kubectl top pod vmstorage-gradient-processing-victoria-metrics-1
NAME                                               CPU(cores)   MEMORY(bytes)   
vmstorage-gradient-processing-victoria-metrics-1   619m         9458Mi 
```
```
-memory.allowedPercent float
Allowed percent of system memory VictoriaMetrics caches may occupy. See also -memory.allowedBytes. Too low a value may increase cache miss rate usually resulting in higher CPU and disk IO usage. Too high a value may evict too much data from OS page cache which will …
```

chore(victoria): lowering memory utilization for cache

---

modules/gradient-processing/templates/values.yaml.tpl

Need to lower the barrier of entry for this because staging isn't able to schedule a second storage node.

chore(victoria): lower request barrier

---

modules/gradient-processing/templates/values.yaml.tpl

Good fun, my determination is that lowering a kubelet scrape interval "too" low will additionally lower the `cadvisor` scrape interval (they're bundled). Which is fine in theory, but with streamParse enabled it looks like scrape requests were timing out, specifically to `kube-state-metrics`. I've seen non-related job scrapes in prometheus break other job scrapes, but this was a weird thing.

fix(victoria): prod hotfixes vmagent

---

gradient-ps-cloud/main.tf

Update the cache list with the new fastai and gradient omni container. Trim some old unused ones.

chore: update cache list with omni container PLA-1235

---

modules/gradient-processing/templates/values.yaml.tpl

This reverts commit d315cf2b1e163d23ee4531598c084bc1c31a8716.

Revert "chore: bump image pull concurrency"

---

gradient-ps-cloud/templates/setup-script.tpl

Having an outside the data center fall back can cause issues with our internal internet.

fix(ps-cloud): remove gcr mirror PLA-1516

---

gradient-ps-cloud/main.tf

Also remove some older containers that have less than 2% usage.

chore: update cache list for new fast.ai course

---

modules/container-registry-mirror/files/docker-registry-mirror.yaml.tpl

The chart's default of NodePort isn't needed and causes issues running multiple replicas on a single node.

fix(container-registry-mirror): service type was incorrect in the chart

---

gradient-metal-gc/main.tf
modules/container-registry-mirror/files/docker-registry-mirror.yaml.tpl

Volumes need to be mountable by more than one instance and should run RWX.

fix(container-registry-mirror): make a volume config for HA PLA-1901

---

gradient-metal-gc/ansible/roles/gradient_common/tasks/install_kubelet_config.yml
gradient-metal-gc/ansible/roles/gradient_control_node/defaults/main.yml
gradient-metal-gc/ansible/roles/gradient_control_node/tasks/main.yml

Running these on user nodes means that resource starvation can effect more than a single user. These should be scheduled on the services nodes.
I have also notice that rancher tunes the scale params way to high by default. There are like 20 running on our cluster. The coredns docs say you need 2 min for ha, and to add another for every ~250 nodes.
Configure Rancher to only run these on the services nodes

fix(graphcore-coredns-rke2): Ensure coredns only runs on services-small

---

modules/gradient-processing/main.tf
modules/gradient-processing/templates/values.yaml.tpl

Several services were found to be running on user worker nodes which causes instability in user workloads and in the mission critical services.
* nats
* cainjector
* metrics-server
* vminsert

fix: run services on service nodes

---

modules/gradient-processing/templates/values.yaml.tpl

The nats cluster configuration was nested under an extra `nats` key and being ignored

fix: nats replicas and jetstream

---

gradient-ps-cloud/main.tf
modules/gradient-processing/main.tf
modules/gradient-processing/templates/values.yaml.tpl

To improve reliability and scalability. We would in particular like to schedule more `vmstorage` nodes to take advantage of sharding.
Now that we have more nodes, I have also added anti affinity rules to prevent co-scheduling thus improving resilience.
This pr does not remove the current `prometheus` C9 node so that I can move the pods gracefully first. The terraform would rip out the node before the scheduler labels are updated thus the cluster would have nowhere to schedule vmselect and vmstorage pods until much later causing unnecessary downtime. I will remove that node at a later time when nothing is running on it.

fix(ps-cloud): put victoria metrics cluster on multiple nodes SIT-255

---

gradient-metal-gc/main.tf

This was under provisioning the vmsingle used in graphcore prod by leaving it at the default.

fix(metal-gc): pass vmsingle resources through

---

modules/gradient-processing/main.tf
modules/gradient-processing/templates/values.yaml.tpl

We're configuring a new rule for our internal apis to interact with for customer metrics.
This new config allows us to provision the new ingress within gradient processing.

chore: victoria ingress rewrite rule

---

modules/gradient-processing/templates/values.yaml.tpl

If they are not the same value you can have another process consume resources and starve your service causing OOMkills  and other issues. If they are set the same you only get OOMkills when the service exceeds its own limits. Given we have smaller boxes we prefer to have services control their own resource destiny.

fix(public-cluster): resource requests = limits

---

common/common.tf
gradient-aws/common.tf
gradient-metal-gc/common.tf
gradient-metal-gc/main.tf
gradient-metal/common.tf
gradient-ps-cloud/common.tf
gradient-ps-cloud/resources.tf
modules/gradient-processing/input.tf
modules/gradient-processing/main.tf
modules/gradient-processing/templates/values.yaml.tpl

* Allow for victoria disk sizes to come through the resources
abstraction allowing graphcore to have a large vmsingle disk
* Turn off the bad nodes detector in graphcore. It only makes sense with
asg backed machines

fix graphcore customizations

---

gradient-metal-gc/ansible/roles/gradient_common/tasks/install_base_packages.yml

Boot strapping issues if this isn't explicitly installed upfront.

fix(graphcore): install containerd package SIT-381

---

gradient-ps-cloud/files/linux-guest-health.sh

Currently if the system never runs the health check the script will
always return unknown meaning the node is never flagged as unhealthy.
Additionally if the system goes readonly then the last output of the
guest health will be read in perpuitity. We want to make sure we are
only getting fresh data.

fix(ps-cloud): make guest health checks more resilient SIT-372

---

gradient-ps-cloud/bin/run
gradient-ps-cloud/files/linux-guest-health.sh
gradient-ps-cloud/node_problem_detector.tf

- Revert "Revert "fix(ps-cloud): make guest health checks more resilient SIT-372 (#447)" (#452)"
- fix(ps-cloud): dont rely on non-present uptime binary SIT-372

fix(ps-cloud): dont rely on non-present uptime binary SIT-372

---

gradient-ps-cloud/resources.tf

Health check fails with exactly 1 cpu. While js code runs single threaded many IO operations do not, giving node exactly 1 cpu can cause stalls.

chore: increase dispatcher resources

---

gradient-ps-cloud/main.tf
gradient-ps-cloud/templates/setup-script.tpl

Pools like `service` need to override the vm type label as the pool otherwise cluster bootstrapping gets confused.

fix(ps-cloud): default to templated pool name
